name: Qodana
on:
  workflow_dispatch:
  pull_request:
  push:
jobs:
  qodana-backend:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      checks: write
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }} 
          fetch-depth: 0
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.SPACE_REGISTRY }}
          username: ${{ secrets.SPACE_LOGIN }}
          password: ${{ secrets.SPACE_TOKEN }}
      - name: 'Qodana Backend'
        uses: JetBrains/qodana-action@v2024.2
        with:
          args: |
            --source-directory,java-part,--config,java-qodana.yaml
          artifact-name: qodana-backend
        env:
            QODANA_TOKEN: ${{ secrets.QODANA_TOKEN_BACKEND }}
  qodana-frontend:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      checks: write
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }} 
          fetch-depth: 0
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.SPACE_REGISTRY }}
          username: ${{ secrets.SPACE_LOGIN }}
          password: ${{ secrets.SPACE_TOKEN }}
      - name: 'Qodana Frontend'
        uses: JetBrains/qodana-action@v2024.2
        with:
          args: |
            --source-directory,vite-typescript-part,--config,js-qodana.yaml
          artifact-name: qodana-frontend
        env:
            QODANA_TOKEN: ${{ secrets.QODANA_TOKEN_FRONTEND }}
